---
kind: Pod
apiVersion: v1
metadata:
  name: coredns
  namespace: openshift-{{ onPremPlatformShortName .ControllerConfig }}-infra
  creationTimestamp:
  deletionGracePeriodSeconds: 65
  labels:
    app: {{ onPremPlatformShortName .ControllerConfig }}-infra-coredns
  annotations:
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    openshift.io/required-scc: privileged
spec:
  volumes:
  - name: resource-dir
    hostPath:
      path: "/etc/kubernetes/static-pod-resources/coredns"
  - name: kubeconfig
    hostPath:
      path: "/etc/kubernetes/kubeconfig"
  - name: conf-dir
    empty-dir: {}
  - name: manifests
    hostPath:
      path: "/opt/openshift/manifests"
  - name: nodeip-configuration
    hostPath:
      path: "/run/nodeip-configuration"
  initContainers:
  - name: render-config
    image: {{ .Images.BaremetalRuntimeCfgBootstrap }}
    command:
    - runtimecfg
    - render
    - "/etc/kubernetes/kubeconfig"
    - "--api-vips"
    - "{{- range $index, $ip := onPremPlatformAPIServerInternalIPs .ControllerConfig }}{{ if gt $index 0 }},{{end}}{{$ip}}{{end}}"
    - "--ingress-vips"
    - "{{- range $index, $ip := onPremPlatformIngressIPs .ControllerConfig }}{{ if gt $index 0 }},{{end}}{{$ip}}{{end}}"
    - "/config"
    - "--out-dir"
    - "/etc/coredns"
    - "--cluster-config"
    - "/opt/openshift/manifests/cluster-config.yaml"
    resources: {}
    volumeMounts:
    - name: kubeconfig
      mountPath: "/etc/kubernetes/kubeconfig"
      mountPropagation: HostToContainer
    - name: resource-dir
      mountPath: "/config"
      mountPropagation: HostToContainer
    - name: conf-dir
      mountPath: "/etc/coredns"
    - name: manifests
      mountPath: "/opt/openshift/manifests"
      mountPropagation: HostToContainer
    - name: nodeip-configuration
      mountPath: "/run/nodeip-configuration"
      mountPropagation: HostToContainer
    imagePullPolicy: IfNotPresent
  containers:
  - name: coredns
    securityContext:
      privileged: true
      readOnlyRootFilesystem: false
    image: {{ .Images.CorednsBootstrap }}
    args:
    - "--conf"
    - "/etc/coredns/Corefile"
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/coredns"
    - name: nodeip-configuration
      mountPath: "/run/nodeip-configuration"
      mountPropagation: HostToContainer
    livenessProbe:
      httpGet:
        path: /health
        port: 18080
        scheme: HTTP
      initialDelaySeconds: 60
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5
    terminationMessagePolicy: FallbackToLogsOnError
  hostNetwork: true
  tolerations:
  - operator: Exists
  priorityClassName: system-node-critical
status: {}
