apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:machine-config-operator:cluster-reader
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
      - subjectaccessreviews
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - machineconfiguration.openshift.io
    resources:
      - containerruntimeconfigs
      - controllerconfigs
      - kubeletconfigs
      - machineconfigpools
      - machineconfignodes
      - machineconfignodes/status
      - machineosconfigs 
      - machineosconfigs/status
      - machineosbuilds
      - machineosbuilds/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.openshift.io
    resources: 
      - images 
      - clusterversions
      - featuregates 
      - nodes
      - nodes/status
      - apiservers
    verbs:
      - get
      - list
      - watch
